# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5341a973eca0db639a5aa9ab2da6086a5a04b2300b2a1c0e84ccc5fb631ec56e9bc6d8e49e6903aba98d949448d06f61bb85b66c5f30a61a841ae9f336e4b2ee

test:
  secret_key_base: 1c67f6bcc001125b354e0874d1a68b923d9d73cfc3fc6f977a702ed68ab1cde55769114ffd3eca99618f52f1cc83269456952d843c230e521f1881df128557e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
