source 'https://rubygems.org'


gem 'rails', '4.2.5'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'haml', '~> 4.0', '>= 4.0.7'
gem 'bootstrap-sass', '~> 3.3', '>= 3.3.6'

# 用户注册、权限管理、第三方登陆
gem 'devise', '~> 3.5', '>= 3.5.3'
gem 'cancancan', '~> 1.10'


# 表单
gem 'simple_form', '~> 3.2', '>= 3.2.1'

# 分页
gem 'will_paginate', '~> 3.0.6'
gem 'will_paginate-bootstrap', '~> 1.0', '>= 1.0.1'

# 验证码
gem 'rucaptcha'


group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'web-console', '~> 2.0'

  gem 'spring'
end

