# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3468df24ba2e697f28385d4a378833415ada06ecf7a69db81588c9b7c692855f3cb0bf452cead1d52e61f1bc90ed7bc9156c64e32e4ed0b6656231eee69594a1

test:
  secret_key_base: 1b0e4064c592d4033967bddb1665766ee7e20645275bbaa2f5166ed87742080375b183075d8129ab2f0aa99114019b3c8572aa875eaa25add77064cd1aeae9d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
