# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99c1c67ccc3630d7bc994edc1cec0e7e040ed5f62c96f35c96626918d7539ca3bea2c5175e6a0b5c1845b473ad6ec4477067cf0eb78510335a4372c85077e5b8

test:
  secret_key_base: c401b57ff359a9e68a40cf08b2105fa8f5cd5beb63c97e06d55ef10cc9d21758abef0b2045319c5e5e90f2f3730caec5889ef8ebb84fd33e6e88ed31b74084e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
